version: '3.8'

services:
  training:
    build:
      context: .
      dockerfile: docker/training/Dockerfile
    image: mlip-training
    volumes:
      - model_storage:/app/models
    restart: on-failure

  inference:
    build:
      context: .
      dockerfile: docker/inference/Dockerfile
    image: mlip-inference
    volumes:
      - model_storage:/app/models
    ports:
      - "8080:8080"
    depends_on:
      - training
    restart: on-failure

#Define a shared volume for the model file
volumes:
  model_storage:
    driver: local
